# Generated by Django 4.1.3 on 2022-11-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='city',
        ),
    ]
